---
- name: index.html on app
  hosts: apps
  gather_facts: false
  become: true

  tasks:
  - name: copy static index.html to tomcat webapps/ROOT/index.html
    template:
      src: index.html.app
      dest: /usr/share/tomcat/webapps/ROOT/index.html