---
- name: deploy postgres
  hosts: appdbs
  gather_facts: false
  become: true

  tasks:
  - name: install postgres
    yum:
      name: postgresql-server
      state: latest
    notify: 
      - initialize postgres
      - initialize postgres some more
  
  - name: enable apache at boot
    service:
      name: postgresql
      enabled: yes

  - name: start postgres
    service:
      name: postgresql.service
      state: started


# only run the next 2 tasks once!
#handlers:
#  - name: initilize postgres
#    command: postgresql-setup initdb
#  - name: initilize postgres some more
#    command: chkconfig postgresql on

