---
- name: deploy postgres
  hosts: appdbs
  gather_facts: false
  become: true

  tasks:
  - name: install postgres
    yum:
      name: postgresql-server
      state: latest
    notify: 
      - initialize_postgres
      - initialize_postgres_more
  
  - name: enable apache at boot
    service:
      name: postgresql
      enabled: yes
    notify: 
      - initialize_postgres
      - initialize_postgres_more

  - name: start postgres
    service:
      name: postgresql.service
      state: started
    notify: 
      - initialize_postgres
      - initialize_postgres_more

  handlers:
  - name: initialize_postgres
    command: postgresql-setup initdb
  - name: initialize_postgres_more
    command: chkconfig postgresql on

